### Makefile -- Preparation of Getopts reference manual

# Author: Michael Grünewald
# Date: Tue Apr 15 07:20:08 CEST 2014

# Getopts (https://github.com/michipili/getopts)
# This file is part of Getopts
#
# Copyright © 2008-2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

ODOC_TITLE=		Getopts library

ODOC_HTML_CSS_FILE=	${PROJECTLIBRARY}/Data/getopts.css
ODOC_HTML_INTRO=	intro.text
ODOC_HTML_CHARSET=	utf-8

.include "ocaml.manual.mk"

### End of file `Makefile'
